### PR TITLE
json file added

### PR DESCRIPTION
**Pull request by suryaval**

### CODE REVIEW

**Comment by pramod1990** [comment]
All good

**Comment by pramod1990** [comment]
All good

**Comment by suryaval** [comment]
`ghprbActualCommit`

**Comment by suryaval** [comment]
```
+ env
ghprbPullId=14
BUILD_URL=http://65.52.235.98:8080/job/pull-request-checks/20/
ghprbPullLink=https://github.com/pramod1990/html/pull/14
HUDSON_SERVER_COOKIE=0560e79f34c8511f
SHELL=/bin/bash
ghprbSourceBranch=surya-testing-now
ghprbPullAuthorEmail=surya.vallabhaneni2@gmail.com
BUILD_TAG=jenkins-pull-request-checks-20
ghprbPullAuthorLogin=suryaval
WORKSPACE=/var/lib/jenkins/workspace/pull-request-checks
JOB_URL=http://65.52.235.98:8080/job/pull-request-checks/
ghprbPullDescription=GitHub pull request #14 of commit 29e4db472c1140cac22bca1c9c0e4b6d12f4fe96, no merge conflicts.
RUN_CHANGES_DISPLAY_URL=http://65.52.235.98:8080/job/pull-request-checks/20/display/redirect?page=changes
USER=jenkins
ghprbAuthorRepoGitUrl=https://github.com/pramod1990/html.git
ghprbCommentBody=null
ghprbPullTitle=json file added
ghprbActualCommitAuthorEmail=noreply@github.com
JENKINS_HOME=/var/lib/jenkins
PATH=/sbin:/usr/sbin:/bin:/usr/bin
RUN_DISPLAY_URL=http://65.52.235.98:8080/job/pull-request-checks/20/display/redirect
_=/bin/env
ghprbPullAuthorLoginMention=@suryaval
PWD=/var/lib/jenkins/workspace/pull-request-checks
HUDSON_URL=http://65.52.235.98:8080/
LANG=en_US.UTF-8
JOB_NAME=pull-request-checks
BUILD_DISPLAY_NAME=#20
sha1=origin/pr/14/merge
BUILD_ID=20
JENKINS_URL=http://65.52.235.98:8080/
ghprbActualCommit=29e4db472c1140cac22bca1c9c0e4b6d12f4fe96
JOB_BASE_NAME=pull-request-checks
HOME=/var/lib/jenkins
SHLVL=3
GIT_BRANCH=surya-testing-now
EXECUTOR_NUMBER=0
JENKINS_SERVER_COOKIE=0560e79f34c8511f
NODE_LABELS=master
ghprbActualCommitAuthor=GitHub
LOGNAME=jenkins
HUDSON_HOME=/var/lib/jenkins
NODE_NAME=master
BUILD_NUMBER=20
JOB_DISPLAY_URL=http://65.52.235.98:8080/job/pull-request-checks/display/redirect
ghprbTargetBranch=master
HUDSON_COOKIE=28ac748c-5a7f-48db-b660-d62a07d25c13
ghprbCredentialsId=github-id
ghprbGhRepository=pramod1990/html
Setting status of 29e4db472c1140cac22bca1c9c0e4b6d12f4fe96 to SUCCESS with url http://65.52.235.98:8080/job/pull-request-checks/20/ and message: 'Build finished. '
All good
```

**Pull request closed without merging**
